### ISSUE TITLE
Issue encountered with Database.countQuery() and ORDER BY filter

### ISSUE THREAD

**Issue by Anuja-dadheech20** [jamessimone/apex-async-processor#2]
An exception will occur in the AsyncProcessor class at line 94 when retrieving the record count using Database.countQuery if the query includes an "ORDER BY" expression. The exception message will read as follows: "System.UnexpectedException: COUNT() and ORDER BY may not be used together."

Could you please review the code snippet below and share your thoughts on whether this is an effective way to resolve the issue?

```
String recordCountQuery = query.replace(query.substringBeforeLast(' from '), 'select count() ');
Integer indexOfOrderBy = query.lastIndexOf('order by');
if (indexOfOrderBy != -1) {
	recordCountQuery = recordCountQuery.replace(query.substring(indexOfOrderBy), ' ');
}
```

**Comment by jamessimone** [comment]
@Anuja-dadheech20 let me take a look at this today - I will push up a fix for this

**Comment by jamessimone** [comment]
@Anuja-dadheech20  - this is all set, thanks for pointing this out!
