### ISSUE TITLE
Unable to execute queueable job multiple times due to FinalizerContext limitation

### ISSUE THREAD

**Issue by vishal4248** [jamessimone/apex-async-processor#3]
I have a scenario where I need to process many records using queueable jobs with a limit on the queueable chunk size. 
For example, if there are 800 account records and the queueable chunk size limit is set to 100, the processing should span across 8 queueable jobs. However, the current implementation is stopped after the 2nd job, which is not the desired behavior.

**Comment by vishal4248** [comment]
Upon investigating this issue, I noticed that the _**execute(System.FinalizerContext fc)**_ method runs only once, causing it to fail to process the subsequent batches of records. After attaching the finalizer, _**this.hasFinalizerBeenAttached**_ is marked as true, preventing the attachment of the finalizer for the next jobs.

To overcome this limitation, I set _**this.hasFinalizerBeenAttached**_ to false before enqueuing the job. This ensures that the finalizer context is attached before each execution of the queueable job and allows for the next requeue if needed.

Please share your thoughts on whether this solution is effective or not.

**Comment by jamessimone** [comment]
that looks good to me - pushed up the change for that!
