### ISSUE TITLE
How to test from trigger when new queueable job is created? Issue on 101 record and beyond.  

### ISSUE THREAD

**Issue by ehsky** [jamessimone/apex-async-processor#4]
Thanks👏 for the great [blog article](https://developer.salesforce.com/blogs/2023/02/exploring-a-combined-async-apex-framework) and this example repo! 🚀

I do have one question regarding bulk testing this from trigger handlers.
Apex.callout limits is on 100, and i see that the example class `BulkSafeHttpProcessor` takes into account this, and creates a new queueable job. Now this works for test on 100 records, but changing the total record creation to 101 and beyond.

My assumption is that Test.setMock() seem to **_not_** be persistent on queueable job 2 and beyond. 

Any hint or help on this is much appreciated.

```java
static void afterInsertBulkPositive() {
		// Arrange
        List<String> integrationMocks = new List<String>();
		List<Account> accList = new List<Account>();
		for (Integer i = 0; i < 200; i++) {
			accList.add(new Account(Name = 'afterInsertBulkPositive_' + i));
                        integrationMocks.add('AddAccount_Success');
		}
		Test.setMock(
			HttpCalloutMock.class,
			new HttpMockUtil(
				integrationMocks
			)
		);
		// Act
		Test.startTest();
		insert accList;
		Test.stopTest();
		// Assert
		List<Account> checks = [
			SELECT Id
			FROM Account
		];
		Assert.areEqual(
			200,
			checks.size(),
			'Expected that 200 records was created.'
		);
		Assert.areEqual(
			2, // <-- Have not managed to come to this assert as the example fails from 101 records
			[
				SELECT COUNT()
				FROM AsyncApexJob
				WHERE
					Status = 'Completed'
					AND JobType = 'BatchApexWorker'
					AND ApexClass.Name = 'AsyncProcessor'
			],
			'Expected to see 2 AsyncApexJob initiated by test.'
		);
	}
```

**Comment by jamessimone** [comment]
@ehsky I've added [ExampleCalloutProcessor](https://github.com/jamessimone/apex-async-processor/blob/main/example-app/classes/ExampleCalloutProcessor.cls) and [ExampleCalloutProcessorTests](https://github.com/jamessimone/apex-async-processor/blob/main/example-app/classes/ExampleCalloutProcessorTests.cls) to show how to do this. Let me know if you need anything else!
